// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BusinessLogic.Models;

public partial class TrainingManagement1Context : DbContext
{
    public TrainingManagement1Context()
    {
    }

    public TrainingManagement1Context(DbContextOptions<TrainingManagement1Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Batch> Batches { get; set; }

    public virtual DbSet<BatchDetail> BatchDetails { get; set; }

    public virtual DbSet<College> Colleges { get; set; }

    public virtual DbSet<Evaluation> Evaluations { get; set; }

    public virtual DbSet<FacultiesSubject> FacultiesSubjects { get; set; }

    public virtual DbSet<Faculty> Faculties { get; set; }

    public virtual DbSet<FeesDetail> FeesDetails { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Trainee> Trainees { get; set; }

    public virtual DbSet<TraineeAssignment> TraineeAssignments { get; set; }

    public virtual DbSet<TraineeEvaluation> TraineeEvaluations { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=.\\sqlexpress02;Initial Catalog=TrainingManagement1;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Batch>(entity =>
        {
            entity.HasKey(e => e.BatchId).HasName("PK__Batches__5D55CE58E5F6696C");
        });

        modelBuilder.Entity<BatchDetail>(entity =>
        {
            entity.HasKey(e => e.BatchDetailId).HasName("PK__BatchDet__B851B70C20370DC0");

            entity.HasOne(d => d.Batch).WithMany(p => p.BatchDetails).HasConstraintName("FK__BatchDeta__Batch__3A81B327");
        });

        modelBuilder.Entity<College>(entity =>
        {
            entity.HasKey(e => e.CollegeId).HasName("PK__Colleges__294095396B80B057");
        });

        modelBuilder.Entity<Evaluation>(entity =>
        {
            entity.HasKey(e => e.EvaluationId).HasName("PK__Evaluati__36AE68F324A3572F");

            entity.HasOne(d => d.Batch).WithMany(p => p.Evaluations).HasConstraintName("FK__Evaluatio__Batch__3B75D760");
        });

        modelBuilder.Entity<FacultiesSubject>(entity =>
        {
            entity.HasKey(e => e.FacultySubjectId).HasName("PK__Facultie__4374186391729806");

            entity.Property(e => e.Discontinue).IsFixedLength();

            entity.HasOne(d => d.Faculty).WithMany(p => p.FacultiesSubjects).HasConstraintName("FK__Faculties__Facul__2B3F6F97");

            entity.HasOne(d => d.Subject).WithMany(p => p.FacultiesSubjects).HasConstraintName("FK__Faculties__Subje__3D5E1FD2");
        });

        modelBuilder.Entity<Faculty>(entity =>
        {
            entity.HasKey(e => e.FacultyId).HasName("PK__Facultie__306F630EFF9EE777");

            entity.Property(e => e.Discontinue).IsFixedLength();
        });

        modelBuilder.Entity<FeesDetail>(entity =>
        {
            entity.HasKey(e => e.FeesId).HasName("PK__FeesDeta__7BD9FD27E7D281B2");

            entity.HasOne(d => d.Batch).WithMany(p => p.FeesDetails).HasConstraintName("FK__FeesDetai__Batch__3E52440B");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__AC1BA3A835AE2384");
        });

        modelBuilder.Entity<Trainee>(entity =>
        {
            entity.HasKey(e => e.TraineeId).HasName("PK__Trainees__3BA911CA8A15C21B");

            entity.Property(e => e.Discontinue)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength();

            entity.HasOne(d => d.Batch).WithMany(p => p.Trainees).HasConstraintName("FK__Trainees__BatchI__4222D4EF");

            entity.HasOne(d => d.College).WithMany(p => p.Trainees).HasConstraintName("FK__Trainees__Colleg__4316F928");
        });

        modelBuilder.Entity<TraineeAssignment>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__TraineeA__32499E77A3981A9C");

            entity.HasOne(d => d.Trainee).WithMany(p => p.TraineeAssignments).HasConstraintName("FK__TraineeAs__Train__3F466844");
        });

        modelBuilder.Entity<TraineeEvaluation>(entity =>
        {
            entity.HasKey(e => e.TraineeEvaluationId).HasName("PK__TraineeE__32FD85A96D276805");

            entity.HasOne(d => d.Evaluation).WithMany(p => p.TraineeEvaluations).HasConstraintName("FK__TraineeEv__Evalu__403A8C7D");

            entity.HasOne(d => d.Trainee).WithMany(p => p.TraineeEvaluations).HasConstraintName("FK__TraineeEv__Train__412EB0B6");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CC4C5F07EC28");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}